spring:
  application:
    name: springsecurity
#  security:
#    user:
#      name: root
#      password: root
server:
  servlet:
    session:
      timeout: 60
  port: 8081
Spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springsecurity
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 1000
      maximum-pool-size: 10
      minimum-idle: 8
      idle-timeout: 600000
      pool-name: HikariPool-springsecurity
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    import: application-prod.yml
    profiles:
      active: prod

logging:
  level:
    org.springframework.security: TRACE
