spring:
  config:
    activate:
      on-profile: prod
  application:
    name: springsecurity
#  security:
#    user:
#      name: root
#      password: root
server:
  port: 8081
  servlet:
    session:
      timeout: 5m
Spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springsecurity
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    org.springframework.security: ERROR
